# -*- coding: utf-8 -*-
"""
Freezes a distributable version of the EAN code file.

    python ean_version.py            produces the next version
    python ean_version.py --version 1   forces the number

Input  : sortie/2-chantier-ean/EAN distributeur.xlsx  (regenerated by ean_global.py)
Output : sortie/2-chantier-ean/EAN distributeur - V1.xlsx

Why a frozen version
--------------------
`EAN distributeur.xlsx` is a working file: it changes with every
collection run. A numbered, dated version with its own notice is
something else: it is what gets handed over, what people agree on, and
what we can come back to in six months knowing what it held.

The cleanup: ambiguous codes
----------------------------
An EAN code identifies ONE product. When the same code turns up on
several of our articles, one of the two is wrong, and nothing says
which. Scanning that code in the warehouse would designate nothing.

These codes are not deleted: they are downgraded to "ambigu", taken out
of the usable set and isolated on their own sheet for arbitration. On a
medical device, you do not make data disappear quietly.

Three families end up there, and they do not share a cause:
  - colour or size variants to which the manufacturer gave a single GTIN
    (a scooter offered in blue, grey and orange): the code is right, it
    is our granularity that is finer;
  - genuinely different products given the same code by an over-broad
    match (a platform and its strap): the code is wrong for all but one;
  - neighbouring ranges confused by their label (a 1-3 years nutrition
    product and the same range for over 3 years).

Only the first is acceptable, and it cannot be told apart from the other
two automatically: hence the arbitration.
"""

from __future__ import annotations

import difflib
import re
import sys
from datetime import date
from pathlib import Path

RACINE = Path(__file__).resolve().parent
sys.path.insert(0, str(RACINE))

import warnings  # noqa: E402

warnings.filterwarnings("ignore")

import pandas as pd  # noqa: E402

import mise_en_forme  # noqa: E402
from extracteurs.base import chemin_lisible, ean_est_valide  # noqa: E402
from main import SORTIE_CHANTIER  # noqa: E402

def _source() -> Path | None:
    """The most recent working file.

    When the workbook is open in Excel, `ean_global` cannot overwrite it
    and writes a timestamped copy next to it. Looking for the canonical
    name only would then freeze a stale version without noticing.
    """
    return mise_en_forme.derniere_version(SORTIE_CHANTIER,
                                          "EAN distributeur.xlsx")

# What each source is worth, in plain words, for the notice
ORIGINE = {
    "tarif": "lu dans le tarif du fournisseur",
    "référence=EAN": "notre référence fournisseur EST un code EAN valide",
    "entrepôt": "scanné sur le produit en entrepôt",
    "eudamed": "déclaré par le fabricant dans EUDAMED, sur la référence exacte",
    "eudamed-modèle": "déclaré dans EUDAMED, rapproché par le modèle",
    "vidal": "publié par VIDAL",
    "libellé": "déduit par concordance de libellé",
}


def _version_suivante() -> int:
    """The number following the last version already produced."""
    numeros = [
        int(trouve.group(1))
        for fichier in SORTIE_CHANTIER.glob("EAN distributeur - V*.xlsx")
        if (trouve := re.search(r" - V(\d+)\.xlsx$", fichier.name))
    ]
    return max(numeros, default=0) + 1


# Words that do not tell two variants of the same product apart: once
# they are removed from the label, two sizes or two colours become one.
DECLINAISON = re.compile(
    r"\b(?:T|TAILLE|T\.)\s*\d+\w*\b"
    r"|\b(?:XS|S|M|L|XL|XXL|XXXL|TU|TS|TM|TL)\b"
    r"|\b(?:NOIR|BLANC|BLEU|ROUGE|GRIS|BEIGE|VERT|ROSE|MARINE|BORDEAUX"
    r"|SABLE|TURQUOISE|ORANGE|JAUNE|VIOLET|MARRON|IVOIRE|LAGON|ANTHRACITE)"
    r"\w*\b"
    r"|\b(?:GAUCHE|DROITE|DROIT)\b",
    re.IGNORECASE)

# Below this similarity, two labels do not describe the same product,
# even once size and colour have been removed.
RESSEMBLANCE_MIN = 0.55


def _socle(libelle) -> str:
    """The label stripped of whatever marks a variant."""
    texte = DECLINAISON.sub(" ", str(libelle or "").upper())
    return re.sub(r"[^A-Z0-9]+", " ", texte).strip()


def _meme_maison(a, b) -> bool:
    """Do two supplier names designate the same company?

    Supplier GE belongs to supplier BF, suppliers A and CS both
    distribute supplier GD: the same code under two different
    "suppliers" is then not an error. The matching alias table already
    knows this, so we reuse it rather than rediscover it.
    """
    import appariement
    if not a or not b or pd.isna(a) or pd.isna(b):
        return False
    if str(a).strip().upper() == str(b).strip().upper():
        return True
    cible = appariement.ALIAS.get(str(a).strip().upper())
    autre = appariement.ALIAS.get(str(b).strip().upper())
    return bool(cible and autre and cible == autre)


def _verdict_partage(groupe: pd.DataFrame) -> tuple[str, str]:
    """What is a code carried by several articles worth? (verdict, reason)

    The same code on two rows is not necessarily an error, and discarding
    it systematically was expensive: 465 rows removed, half of which
    carried an exact code.

    Three situations justify it:

      - a single supplier reference across all the rows: these are
        DUPLICATE WMS articles, not wrong codes. One and the same
        cervical collar occupies three article codes;
      - two supplier names for one and the same company;
      - size or colour variants to which the manufacturer gave a single
        GTIN: our granularity is then finer than theirs.

    What is left is the case where the references AND the labels both
    diverge: there the code is wrong for all but one, and nothing says
    which.
    """
    references = {str(r).strip() for r in groupe["Réf. fournisseur"].dropna()}
    fournisseurs = [f for f in groupe["Fournisseur"].dropna().unique()]

    if len(references) <= 1:
        return "oui", "articles WMS en doublon — même référence fournisseur"

    if len(fournisseurs) > 1 and all(
            _meme_maison(fournisseurs[0], f) for f in fournisseurs[1:]):
        return "oui", "même société sous deux noms"

    socles = {_socle(x) for x in groupe["Désignation"]}
    if len(socles) == 1:
        return "oui", "déclinaisons d'un même produit — GTIN de gamme"

    libelles = [str(x) for x in groupe["Désignation"]]
    ressemblance = min(
        difflib.SequenceMatcher(None, _socle(libelles[0]), _socle(x)).ratio()
        for x in libelles[1:])
    if ressemblance >= RESSEMBLANCE_MIN:
        return "oui", f"libellés concordants ({ressemblance:.0%})"

    return "NON — code ambigu", "références et libellés divergents"


def _verifies_au_libelle() -> set[str]:
    """The EUDAMED codes compared against the label one by one, and kept.

    The only exception to the EUDAMED withdrawal: these were not taken on
    trust, they were judged piece by piece by `ean_verifier_libelle.py`.
    If the file is missing the set is empty, and we then withdraw ALL of
    EUDAMED, which is the cautious behaviour.
    """
    fichier = SORTIE_CHANTIER / "eudamed_verification_libelle.xlsx"
    if not fichier.exists():
        return set()
    try:
        v = mise_en_forme.lire(fichier, "Verdicts", "Code article")
    except SystemExit:
        return set()
    retenus = v[v["Verdict"].isin(["CONFIRMÉ", "CORRIGÉ"])]
    return set(retenus["Code article"].astype(str).str.strip())


def _marquer_ambigus(df: pd.DataFrame) -> pd.DataFrame:
    """Rules on every code: usable, or to be arbitrated."""
    avec_code = df["Code EAN"].notna()
    comptes = df.loc[avec_code, "Code EAN"].value_counts()
    df["Articles portant ce code"] = (
        df["Code EAN"].map(comptes).fillna(0).astype(int))

    df["Exploitable"] = "oui"
    df["Motif du partage"] = ""
    df.loc[~avec_code, "Exploitable"] = "— pas de code"

    for code in comptes[comptes > 1].index:
        lignes = df["Code EAN"] == code
        verdict, motif = _verdict_partage(df.loc[lignes])
        df.loc[lignes, "Exploitable"] = verdict
        df.loc[lignes, "Motif du partage"] = motif
        if verdict.startswith("NON"):
            df.loc[lignes, "Fiabilité"] = "ambigu"

    # A wrong GS1 check digit has no business being here, but we check it
    # anyway: it is the cheapest control in the file.
    invalide = avec_code & ~df["Code EAN"].map(ean_est_valide)
    df.loc[invalide, "Exploitable"] = "NON — clé GS1 invalide"
    df.loc[invalide, "Fiabilité"] = "invalide"

    # An EAN-8 in a medical equipment price list does not exist: that
    # format is reserved for packaging too small to carry an EAN-13.
    court = avec_code & (df["Code EAN"].str.len() < 13)
    df.loc[court, "Exploitable"] = "NON — 8 chiffres, pas un EAN produit"
    df.loc[court, "Fiabilité"] = "invalide"

    # EUDAMED IS NO LONGER A RELIABLE SOURCE, FOR ANY OF ITS ROWS (16/09).
    #
    # The rule first targeted only references shorter than nine
    # characters, 1 321 codes. Three independent measurements showed that
    # the defect does not stop there:
    #   - compared against the label in EUDAMED itself, 468 codes judged:
    #     354 REJETÉ, only 19 saved (CONFIRMÉ or CORRIGÉ);
    #   - compared against the supplier price lists, 248 codes: 75
    #     contradicted, i.e. 30 % wrong where the price list is
    #     authoritative;
    #   - GS1 prefix agreement: 27.8 %, against 100 % for a price list.
    #
    # The cost of the withdrawal is low, and it was measured before
    # deciding: over the frozen scope, 85 articles lose their code and
    # coverage goes from 71.4 % to 69.7 %. One and a half points against
    # a source at least a third of which is wrong, and wrong silently.
    #
    # Nothing is deleted: the code, its source and its reference stay in
    # the log, that is what the log is for. We withdraw an ASSERTION, not
    # a piece of data. The 19 codes checked against the label keep their
    # 'sûr': those were compared one by one.
    eudamed = df["Source"].fillna("").str.strip().str.startswith("eudamed")
    verifies = _verifies_au_libelle()
    garde = df["Code article"].astype(str).str.strip().isin(verifies)
    df.loc[eudamed & ~garde, "Fiabilité"] = "à vérifier"
    print(f"  EUDAMED: {int((eudamed & ~garde).sum())} codes moved to "
          f"'à vérifier', {int((eudamed & garde).sum())} kept as 'sûr' "
          f"(checked against the label)")
    return df


def _notice(df: pd.DataFrame, version: int) -> pd.DataFrame:
    """What a reader needs to know before using the file."""
    exploitables = df[df["Exploitable"] == "oui"]
    ambigus = df[df["Exploitable"].str.startswith("NON")]
    actifs = df[df["Actif"].astype(str).str.upper().isin(["OUI", "1", "TRUE"])]
    actifs_ok = actifs[actifs["Exploitable"] == "oui"]

    lignes = [
        ("CODES EAN DU DISTRIBUTEUR",
         f"version {version} — {date.today():%d/%m/%Y}"),
        ("", ""),
        ("CE QUE CONTIENT LE FICHIER", ""),
        ("Articles couverts",
         f"{len(df)} — l'ensemble du périmètre métier, hors SE, "
         f"forfait et location"),
        ("Codes exploitables",
         f"{len(exploitables)} ({len(exploitables)/len(df):.0%})"),
        ("Sur les articles actifs",
         f"{len(actifs_ok)} sur {len(actifs)} ({len(actifs_ok)/max(len(actifs),1):.0%})"),
        ("Codes écartés", f"{len(ambigus)} — voir l'onglet « Codes ambigus »"),
        ("", ""),
        ("D'OÙ VIENNENT LES CODES", ""),
    ]
    for source, compte in exploitables["Source"].value_counts().items():
        lignes.append((f"{source} — {compte}",
                       ORIGINE.get(source, "source non documentée")))

    lignes += [
        ("", ""),
        ("COMMENT ILS SONT VÉRIFIÉS", ""),
        ("Clé de contrôle GS1",
         "tout code dont la clé de contrôle est fausse est écarté. "
         "Aucun n'a été trouvé dans cette version."),
        ("Unicité",
         "un code EAN identifie un produit. Un code porté par plusieurs "
         "de nos articles est retiré du lot exploitable : rien ne dit "
         "lequel il désigne vraiment."),
        ("GTIN-14",
         "un code de 14 chiffres commençant par 0 est l'unité de vente "
         "écrite sur 14 positions : il est ramené en EAN-13. Les "
         "indicateurs 1 à 8 désignent un carton ou une palette et ne "
         "sont pas retenus comme code produit."),
        ("Codes ACL13",
         "les codes ACL des officines (préfixe 3401) sont de vrais "
         "EAN-13 et sont retenus comme tels."),
        ("", ""),
        ("CE QUE LE FICHIER NE DIT PAS", ""),
        ("Codes déduits",
         "les codes issus d'une concordance de libellé ou d'un modèle "
         "EUDAMED sont marqués « probable » ou « à vérifier ». Ils "
         "n'ont pas été lus sur le produit : les contrôler avant de "
         "s'en servir pour une commande ou une traçabilité de lot."),
        ("Conditionnement",
         "le code retenu est celui de l'UNITÉ DE VENTE. Le code du "
         "carton, quand le fournisseur le publie, est conservé à part "
         "et ne figure pas ici."),
        ("Articles sans code",
         f"{int(df['Code EAN'].isna().sum())} articles restent sans code. "
         f"La collecte EUDAMED par référence est en cours et les "
         f"complétera progressivement."),
        ("", ""),
        ("RÉGÉNÉRER", ""),
        ("Commande",
         "python main.py  puis  python ean_global.py  puis  "
         "python ean_version.py"),
        ("Fichier de travail",
         "EAN distributeur.xlsx — celui-ci change à chaque collecte ; la "
         "version numérotée, elle, ne bouge plus."),
    ]
    return pd.DataFrame(lignes, columns=["", " "])


def main() -> None:
    source = _source()
    if source is None:
        raise SystemExit("Run first: python ean_global.py")
    print(f"source: {source.name}")

    version = _version_suivante()
    for argument in sys.argv[1:]:
        if argument.startswith("--version"):
            version = int(argument.split("=")[-1] if "=" in argument
                          else sys.argv[sys.argv.index(argument) + 1])

    df = pd.read_excel(chemin_lisible(source), sheet_name="Codes EAN",
                       skiprows=3, dtype=str)
    df = _marquer_ambigus(df)

    # Where to find the product. Without this column, an article with no
    # code has to be hunted for in the store before it can be scanned;
    # with it, the list of gaps becomes a picking round.
    import carte_entrepot
    lieux = carte_entrepot.par_article()
    if not lieux.empty:
        cle = df["Code article"].astype(str).str.strip()
        for colonne in lieux.columns:
            df[colonne] = cle.map(lieux[colonne])
        localises = int(df["Emplacement"].notna().sum())
        print(f"  {localises} articles located "
              f"({localises/len(df):.0%})")

    exploitables = df[df["Exploitable"] == "oui"]
    ambigus = df[df["Exploitable"].str.startswith("NON")].sort_values(
        ["Code EAN", "Désignation"])
    sans_code = df[df["Code EAN"].isna()]

    # Duplicate WMS articles are not this project's business: the code is
    # right, it is the database that describes the same product twice. We
    # flag it without touching it, as the working rule requires.
    doublons = df[df["Motif du partage"].str.startswith(
        "articles WMS en doublon", na=False)].sort_values(
        ["Réf. fournisseur", "Code article"])
    if not doublons.empty:
        retours = RACINE / "perimetre" / "retours"
        retours.mkdir(parents=True, exist_ok=True)
        chemin_retour = retours / (
            f"doublons articles WMS — {date.today():%Y-%m-%d}.xlsx")
        colonnes_retour = [c for c in
                           ["Code article", "Référence", "Désignation",
                            "Fournisseur", "Réf. fournisseur", "Code EAN",
                            "Articles portant ce code", "Actif", "Stock"]
                           if c in doublons.columns]
        with pd.ExcelWriter(chemin_retour, engine="openpyxl") as writer:
            doublons[colonnes_retour].to_excel(
                writer, sheet_name="À vérifier dans le WMS", index=False,
                startrow=3)
        mise_en_forme.formater(chemin_retour, options={
            "À vérifier dans le WMS": {
                "ligne_entete": 4, "figer_colonne": 2,
                "titre": "Articles du WMS portant la même référence "
                         "fournisseur",
                "sous_titre": (
                    f"{len(doublons)} lignes, "
                    f"{doublons['Réf. fournisseur'].nunique()} références | "
                    f"le code EAN est juste : c'est la base qui décrit "
                    f"plusieurs fois le même produit. Rien n'a été modifié "
                    f"ici."),
            }})
        print(f"  {len(doublons)} duplicate articles flagged "
              f"-> {chemin_retour.parent.name}/{chemin_retour.name}")

    synthese = (exploitables.groupby(["Source", "Fiabilité"])
                .size().reset_index(name="Codes")
                .sort_values("Codes", ascending=False))

    chemin = SORTIE_CHANTIER / f"EAN distributeur - V{version}.xlsx"
    colonnes = ["Code article", "Référence", "Désignation", "Fournisseur",
                "Réf. fournisseur", "Code EAN", "Source", "Fiabilité",
                "Exploitable", "Motif du partage",
                "Articles portant ce code",
                "Zone", "Emplacement", "Autres emplacements",
                "Nb emplacements", "Actif", "Stock", "Type", "Famille"]
    colonnes = [c for c in colonnes if c in df.columns]

    with pd.ExcelWriter(chemin, engine="openpyxl") as writer:
        df[colonnes].to_excel(writer, sheet_name="Codes EAN", index=False,
                              startrow=3)
        ambigus[colonnes].to_excel(writer, sheet_name="Codes ambigus",
                                   index=False, startrow=3)
        sans_code[colonnes].to_excel(writer, sheet_name="Sans code",
                                     index=False, startrow=3)
        synthese.to_excel(writer, sheet_name="Synthèse", index=False,
                          startrow=3)
        _notice(df, version).to_excel(writer, sheet_name="Notice",
                                      index=False)

    actifs = df[df["Actif"].astype(str).str.upper().isin(["OUI", "1", "TRUE"])]
    actifs_ok = int((actifs["Exploitable"] == "oui").sum())
    mise_en_forme.formater(chemin, options={
        "Codes EAN": {
            "ligne_entete": 4, "figer_colonne": 3,
            "titre": f"Codes EAN du distributeur — version {version}",
            "sous_titre": (
                f"{len(exploitables)} codes exploitables sur {len(df)} "
                f"articles | {actifs_ok} des {len(actifs)} articles actifs | "
                f"arrêté au {date.today():%d/%m/%Y}"),
        },
        "Codes ambigus": {
            "ligne_entete": 4, "figer_colonne": 3,
            "titre": "Codes portés par plusieurs articles",
            "sous_titre": (
                "Un code EAN identifie un produit. Ceux-ci en désignent "
                "plusieurs : rien ne dit lequel. Écartés du lot "
                "exploitable, conservés ici pour arbitrage."),
        },
        "Sans code": {
            "ligne_entete": 4, "figer_colonne": 3,
            "titre": "Articles encore sans code EAN",
            "sous_titre": (
                f"{int(sans_code['Emplacement'].notna().sum())} d'entre eux "
                f"ont un emplacement connu : ceux-là peuvent être relevés "
                f"en descendant l'allée. La collecte EUDAMED complétera le "
                f"reste."
                if "Emplacement" in sans_code.columns
                else "La collecte EUDAMED par référence est en cours et les "
                     "complétera progressivement"),
        },
        "Synthèse": {
            "ligne_entete": 4,
            "titre": "D'où viennent les codes retenus",
            "sous_titre": "Par source et par niveau de fiabilité",
        },
    })

    print(f"version {version}, {date.today():%d/%m/%Y}")
    print(f"  {len(df)} articles")
    print(f"  {len(exploitables)} usable codes "
          f"({len(exploitables)/len(df):.0%})")
    print(f"  {actifs_ok} of {len(actifs)} active articles "
          f"({actifs_ok/max(len(actifs),1):.0%})")
    print(f"  {len(ambigus)} discarded as ambiguous")
    print(f"  {len(sans_code)} without a code")
    print(f"\n  -> {chemin}")


if __name__ == "__main__":
    main()
